### ISSUE TITLE
[Bug] ERR_CHILD_PROCESS_STDIO_MAXBUFFER error when trying to import highlights

### ISSUE THREAD

**Issue by jun6lee** [bandantonio/obsidian-apple-books-highlights-plugin#11]
**Description the bug**

Also include the following details:
- Error behavior: intermittent/permanent.
- Error occurs when:
  - [x] Importing a single book
  - [x] Importing all books
  - [x] All the above
- Number of books and highlights (approximately): <in the hundreds for sure>

**General information**
- Plugin version: [e.g. 1.2.0]
- Obsidian version: [1.5.8]
- MacOS version: [Sonoma 14.3.1]

**To Reproduce**
1. Go to '...'  Apple Books - Import Highlights -- Single Book
2. A blank popup appears, doesn't show my books
3. See error

**Expected behavior**
Highlights come through.

**Screenshots**
<img width="534" alt="Screenshot 2024-03-15 at 16 53 36" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/6542146/e0eb1598-bb14-45b3-9c5c-54c7acbdd61c">

**Comment by bandantonio** [comment]
Please provide more info:

- What is your plugin version?
- How many books/highlights do you have (approximately)?
- When does the error occur: when importing a single book/all books/both ?
- Is the error intermittent or permanent?
- Describe the steps that lead to the error (be as specific as possible)

**Comment by jun6lee** [comment]
Updated in original comment

**Comment by jun6lee** [comment]
Have tried this on a different machine and with a new vault. Same issue.

**Comment by jun6lee** [comment]
I think it's a node issue not handling my quantity?
This is the error caught when trying to get the list of books:

Importing a single book > where it shows the popup where books would show, but unpopulated.

```
const captureLargerStackTrace = hideStackFrames(
  function captureLargerStackTrace(err) {
    const stackTraceLimitIsWritable = isErrorStackTraceLimitWritable();
    if (stackTraceLimitIsWritable) {
      userStackTraceLimit = Error.stackTraceLimit;
      Error.stackTraceLimit = Infinity;
    }
    ErrorCaptureStackTrace(err);
    // Reset the limit
    if (stackTraceLimitIsWritable) Error.stackTraceLimit = userStackTraceLimit;

    return err;
  });
```

**Comment by jun6lee** [comment]
That said, it's how it's handled, as the plugin I was using prior still works:
https://github.com/bingryan/obsidian-ibook-plugin

**Comment by jun6lee** [comment]
Do you have the bandwidth o help?

**Comment by bandantonio** [comment]
Hi. I'm a bit busy with some work stuff, but I hope to release a fix close to the end of the week. 

There are also some strange bugs reported by users in the Obsidian's forum, I believe it worth fixing them as well.
