### ISSUE TITLE
FR: Naming of Highlight File

### ISSUE THREAD

**Issue by jun6lee** [bandantonio/obsidian-apple-books-highlights-plugin#13]
I have some whole books that I've converted from ePub to HTML to Markdown in my vault.

---

With my workflow, I have daily notes in which I link the book if I read some part of it that day.
I collect this info in other periodic notes for other purposes.

Long story short, if the highlights coming in have the same title, some links in my daily notes will assume to link to the file with the highlights, rather than the book, so as well as folder, it would be a useful tweak if I could append something to the name of the file created. Eg: " - highlights"

**Comment by bandantonio** [comment]
It seems like [Aliases](https://help.obsidian.md/Linking+notes+and+files/Aliases) would do the trick for you.

**Comment by bandantonio** [comment]
Thanks for the details.

I believe you can modify your template for highlights by adding `alias` to the frontmatter as follows:

```
---
alias: {{{bookTitle}}}-HL
---

<the rest of the template>
```

In this way, your links that are pointing to books will be resolved properly, still allowing you to type the same `[[BookTitle]]` and choose the pre-populated alias that will be resolved to the corresponding book with highlights:

<img width="453" alt="" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/16765690/85af06c9-5609-4e1a-9ecc-8f3fbc0c2f0c">

That's how direct link and alias get resolved:
<img width="449" alt="" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/16765690/6ef746cf-15cd-4b18-8d97-2e66660418ce">

<img width="193" alt="" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/16765690/84d3e2f8-e522-470f-8234-392d910ba533">

**Comment by jun6lee** [comment]
Okay, didn't get to play enough.
I'll test this out once I can get highlights in, can't seem to resolve that issue yet.

**Comment by bandantonio** [comment]
Closed due to inactivity
