### ISSUE TITLE
Parse error near line 2: no such table: ZAEANNOTATION

### ISSUE THREAD

**Issue by vsiisv** [bandantonio/obsidian-apple-books-highlights-plugin#17]
**Description the bug**
The plugin is not working. not with the commands, not with the icon in sidebar.
getting this error in console output:

`Error: Command failed: echo "
			SELECT ZASSETID, ZTITLE, ZAUTHOR, ZGENRE, ZLANGUAGE, ZLASTOPENDATE, ZCOVERURL
			FROM ZBKLIBRARYASSET
			WHERE ZPURCHASEDATE IS NOT NULL" | sqlite3 ~/Downloads/test-BKLibrary.sqlite -json
Parse error near line 2: no such table: ZBKLIBRARYASSET`

`Error: Command failed: echo "
			SELECT ZANNOTATIONASSETID, ZFUTUREPROOFING5, ZANNOTATIONREPRESENTATIVETEXT, ZANNOTATIONSELECTEDTEXT, ZANNOTATIONNOTE, ZANNOTATIONCREATIONDATE, ZANNOTATIONMODIFICATIONDATE, ZANNOTATIONSTYLE
			FROM ZAEANNOTATION
			WHERE ZANNOTATIONSELECTEDTEXT IS NOT NULL
			AND ZANNOTATIONDELETED IS 0" | sqlite3 ~/Downloads/empty-AEAnnotation_v10312011_1727_local.sqlite -json
Parse error near line 2: no such table: ZAEANNOTATION`

Also include the following details:
- Error behavior: intermittent/permanent.
- Error occurs when:
  - [x] Importing a single book
  - [x] Importing all books
  - [x] All the above
- Number of books and highlights (approximately)

**General information**
- Plugin version: 1.2.2
- Obsidian version: 1.5.12
- MacOS version: Sonoma 14.4

**To Reproduce**
1. option+command --> Apple Books import command
2. with icon in sidebar
3. See error

**Expected behavior**
importing some highlights

**Screenshots**

**Additional context**
getting this error in console:

**Comment by roman1gan** [comment]
me too 🙁

**Comment by bandantonio** [comment]
@vsiisv @roman1gan Thanks for reporting 🤝.
This was an unintentional bug after testing responses from databases. Please update the plugin to the latest [`1.2.3`](https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/releases/tag/1.2.3) version.

**Comment by vsiisv** [comment]
Thanks a lot. 
It works =)
