### ISSUE TITLE
[Bug] Error when callout meets newline

### ISSUE THREAD

**Issue by modatwork** [bandantonio/obsidian-apple-books-highlights-plugin#21]
Hi bandantonio, thanks for sharing this nice plugin.

**Description the bug**

Also include the following details:
- Error behavior: permanent.
- Error occurs when:
  - [ ] Importing a single book
  - [ ] Importing all books
  - [x] All the above
- 1  book and 1 highlight

**General information**
- Plugin version: 1.2.3
- Obsidian version: 1.6.5
- MacOS version: 13.5.2

**To Reproduce**
1. Create a highlight for a paragraph which contains newlines
2. Add Obsidian Callout syntax to the plugin template as showed below
3. Import highlights
4. The highlight is not quoted correctly

**Expected behavior**

All the text from the highlight is quoted.

**Screenshots**

the current output:
<img width="637" alt="image" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/129473364/58194c5e-a16d-46d8-8bb8-59e5c31ceacb">

<img width="698" alt="image" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/129473364/bba3924e-1931-482c-bfec-340d281897db">

expected output:

<img width="746" alt="image" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/129473364/beb42ccd-651f-4b51-9112-68b57ff8cb7f">

<img width="727" alt="image" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/129473364/d92dd245-256c-4721-963f-b2bf2526a571">

**Additional context**

The template used:

```
{{#each annotations}}
----

> [!QUOTE]
>  {{{highlight}}}

{{/each}}
```

**Comment by bandantonio** [comment]
@modatwork Thanks you for the feedback and submitting the report. Recently, I stumbled upon a similar behavior with regular highlights, so it's time to fix it 🙃

**Comment by bandantonio** [comment]
@modatwork I spent some time with this bug and basically, there are two options available:

1 - preserve newlines. The only reasonable way for this option to work (at least, with the current tooling) is to add a tiny bit of HTML to the resulting Markdown file, like this:

Rendered Markdown file:

```
> [!QUOTE]
>  Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>
Sed non risus.
Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat.
```

Preview:

<img width="660" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/16765690/3b98881f-539c-4366-a7c7-afb4d87abe7e">

2 - remove newlines. Still an option, the only minor issue is a slight decrease of readability

```
> [!QUOTE]
>  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Sed non risus.
Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat.
```

<img width="659" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/16765690/30cb22d8-5eb1-40b2-b2ea-f24b9f24aa8b">

----

What option you like more? Personally, I feel like adding a tiny bit of HTML won't hurt, as many people use HTML snippets in their Obsidian vaults as well. Plus it will preserve the original structure and won't impact readability.

**Comment by modatwork** [comment]
`<br>` should work. But I found that my case is a little special. The newline begins with 4 spaces. And Obsidian can't render that correctly without a `>` in each line.

**Comment by modatwork** [comment]
Another option is to add an `{{#each}}{{/each}}` syntax for each line of the highlight text. I'm not sure if that's a good idea to add this complexity.

**Comment by bandantonio** [comment]
> `<br>` should work. But I found that my case is a little special. The newline begins with 4 spaces. And Obsidian can't render that correctly without a `>` in each line.

The actual number of spaces is not an issue (however, fun fact, almost all of my highlights have 2 spaces indents, even those taken from bullet points 🤔). Anyway, it seems like I managed to workaround the bug by sacrificing newlines.
So, for example, the rendered highlight from your example will look like that:

```
> [!QUOTE]
>  Chapter 1 introduces the terminology and approach
that we’re going to use throughout this book. It examines what we actually mean by
words like reliability, scalability, and maintainability, and how
we can try to achieve these goals.
```

<img width="657" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/16765690/ee9b5423-e6ca-4fba-ac1f-d65c6b844890">
