### ISSUE TITLE
Cannot install the plugin on Obsidien v1.6.5

### ISSUE THREAD

**Issue by absorpheus** [bandantonio/obsidian-apple-books-highlights-plugin#22]
When trying to install the plugin in Obsidien, the following error appears:

**Failed to install plugin "Apple Books - Import Highlights"**

Using Obsidien (Current version: v1.6.5, Installer version: v1.6.5)

Tested on macOS Sonoma 14.2.1

**Console tab**

<img width="1326" alt="console-1" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/19255312/bd5ec1ef-105e-4cb3-8af7-d6f19148c850">

**Obsidien (app.js)**

<img width="2160" alt="console-2" src="https://github.com/bandantonio/obsidian-apple-books-highlights-plugin/assets/19255312/03446f22-ca75-4689-b9d9-8a8efe88ea5e">

It seems there is an error when making the request to fetch the plugin.

I think this is a problem with Obsidien itself and not to do with your plugin as I was able to install the plugin manually.

**Update:**
So I've managed to install it 'manually' using 'Build a plugin'
https://docs.obsidian.md/Plugins/Getting+started/Build+a+plugin

**Comment by bandantonio** [comment]
@absorpheus Thank you for the report.
The issue was related to an unintentional version bump with no artifacts attached.

I reverted the plugin back to the latest (1.2.3) version. Please check that everything OK on your side.

**Comment by absorpheus** [comment]
Thank you for your swift reply. I can confirm it is now working!

**Comment by bandantonio** [comment]
Great, thank you for the confirmation and for waiting patiently for the fix.
